### PR TITLE
style

### PR DESCRIPTION
**Pull request by LeoNardoRR**
Hi, i created a style in your simple button and add identation in vue.js code, i used scale but has a .native-button in your code that prevents me from changing the button-radius, I can't find this class

### CODE REVIEW

**Comment by LeoNardoRR** [comment]
Hi again, i find the problem lmao, ajusted the scale for (1.02) and add scale in the icon button

**Comment by LeoNardoRR** [comment]
Hi, i delete the button delete and include a new design for the login page, u can review?

**Comment by LeoNardoRR** [comment]
Now i applied button readjustment responsiveness

**Comment by pferreirafabricio** [comment]
Hi @LeoNardoRR, thanks for your contribution!

These changes don't apply any improvements to the project in an effective way so I will close this for now.

Feel free to create a new issue to discuss new ideas for improvements.

**Pull request closed without merging**
